--1.- CREAR BASE DE DATOS LLAMADA MOVIES

CREATE DATABASE movies;

--2.- CREAR  LA TABLA LLAMADA PELICULAS

CREATE TABLE peliculas(
id INT PRIMARY KEY,
peliculas VARCHAR(255),
ano_estreno INT,
director VARCHAR(255)
);

--2.- CREAR LA TABLA LLAMADA REPARTO

CREATE TABLE reparto(
id SERIAL PRIMARY KEY, 
pelicula_id INT,
actor VARCHAR (255),
FOREIGN KEY (pelicula_id)
REFERENCES peliculas (id )
);


-- CARGAR ARCHIVO CSV DESDE PSQL TOOL




SELECT * FROM peliculas;
SELECT * FROM reparto;



--3.- OBTENER EL ID DE LA PELICULA TITANIC

SELECT id FROM peliculas WHERE peliculas='Titanic';


--4.- LISTAR TODOS LOS ACTORES QUE APARECEN EN LA PELICULA TITANIC

SELECT actor AS actores FROM reparto WHERE pelicula_id=(SELECT id FROM peliculas WHERE peliculas='Titanic');


--5.- CONSULTAR EN CUANTAS PELICULAS DEL TOP 100 PARTICIPA HARRINSON FORD.

SELECT COUNT(pelicula_id) AS total_peliculas_H_Ford FROM reparto WHERE actor='Harrison Ford';


--6.- INDICAR LAS PELICULAS ESTRENADAS ENTRE LOS AÑOS 1990 Y 1999 ORDENADAS POR TITULO DE MANERA ASCENDENTE

SELECT * FROM peliculas WHERE ano_estreno BETWEEN 1990 AND 1999 ORDER BY peliculas ASC;


--7.- HACER UNA CONSULTA SQL QUE MUESTRE LOS TITULOS CON SU LONGITUD , LA LONGITUD DEBE SER NOMBRADO PARA LA CONSULTA COMO longitud_titulo

SELECT peliculas, LENGTH(peliculas) AS longitud_titulo FROM peliculas;


--8.- CONSULTAR  CUAL ES LA LONGITUD MAS GRANDE ENTRE TODOS LOS TITULOS DE LAS PELICULAS

SELECT MAX (LENGTH(peliculas)) AS longitud_maxima FROM peliculas;


--2.- APLICAR EL TRUNCADO A LAS TABLAS

TRUNCATE TABLE peliculas;
TRUNCATE TABLE reparto;
